POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de React Native"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses?search=react

###

GET http://localhost:3333/courses?orderby=title&page=1

###

GET http://localhost:3333/courses/0e5db61d-99ba-4659-a421-bc3cdf829037